name: Publish PowerShell Module

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
        shell: pwsh
        run: |
          Publish-Module -Path '.\PSZoom' -NuGetApiKey $env:NUGETAPIKEY -Verbose
